language: go
go:
 - 1.x
 - tip

go_import_path: kmodules.xyz/custom-resources

env:
  global:
  - GOFLAGS=-mod=vendor
  - GO111MODULE=on

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

install: true

script:
 - go build -v ./...
 - go test -v ./...
