/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kmodules.xyz/custom-resources/apis/auditor/v1alpha1"
	scheme "kmodules.xyz/custom-resources/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SiteInfosGetter has a method to return a SiteInfoInterface.
// A group's client should implement this interface.
type SiteInfosGetter interface {
	SiteInfos() SiteInfoInterface
}

// SiteInfoInterface has methods to work with SiteInfo resources.
type SiteInfoInterface interface {
	Create(ctx context.Context, siteInfo *v1alpha1.SiteInfo, opts v1.CreateOptions) (*v1alpha1.SiteInfo, error)
	Update(ctx context.Context, siteInfo *v1alpha1.SiteInfo, opts v1.UpdateOptions) (*v1alpha1.SiteInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SiteInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SiteInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SiteInfo, err error)
	SiteInfoExpansion
}

// siteInfos implements SiteInfoInterface
type siteInfos struct {
	client rest.Interface
}

// newSiteInfos returns a SiteInfos
func newSiteInfos(c *AuditorV1alpha1Client) *siteInfos {
	return &siteInfos{
		client: c.RESTClient(),
	}
}

// Get takes name of the siteInfo, and returns the corresponding siteInfo object, and an error if there is any.
func (c *siteInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SiteInfo, err error) {
	result = &v1alpha1.SiteInfo{}
	err = c.client.Get().
		Resource("siteinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SiteInfos that match those selectors.
func (c *siteInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SiteInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SiteInfoList{}
	err = c.client.Get().
		Resource("siteinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested siteInfos.
func (c *siteInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("siteinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a siteInfo and creates it.  Returns the server's representation of the siteInfo, and an error, if there is any.
func (c *siteInfos) Create(ctx context.Context, siteInfo *v1alpha1.SiteInfo, opts v1.CreateOptions) (result *v1alpha1.SiteInfo, err error) {
	result = &v1alpha1.SiteInfo{}
	err = c.client.Post().
		Resource("siteinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(siteInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a siteInfo and updates it. Returns the server's representation of the siteInfo, and an error, if there is any.
func (c *siteInfos) Update(ctx context.Context, siteInfo *v1alpha1.SiteInfo, opts v1.UpdateOptions) (result *v1alpha1.SiteInfo, err error) {
	result = &v1alpha1.SiteInfo{}
	err = c.client.Put().
		Resource("siteinfos").
		Name(siteInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(siteInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the siteInfo and deletes it. Returns an error if one occurs.
func (c *siteInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("siteinfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *siteInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("siteinfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched siteInfo.
func (c *siteInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SiteInfo, err error) {
	result = &v1alpha1.SiteInfo{}
	err = c.client.Patch(pt).
		Resource("siteinfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
